[project]
name = "minigpt-training"
version = "0.1.0"
description = "MiniGPT训练框架 - Mac优化版本"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch>=2.0.0",
    "numpy>=1.21.0",
    "matplotlib>=3.5.0",
    "tqdm>=4.60.0",
    "psutil>=5.8.0",
]
